import argparse
import retro


if __name__ == "__main__":
  # lets begin with testing atari games in stable retro and stable baselines
  parser = argparse.ArgumentParser()
  parser.add_argument("movie_file", help="recording generated by stable retro.")
  parser.add_argument(
    "roms_path",
    help="Path to directory with directories of roms. "
    "Go to https://stable-retro.farama.org/integration/#using-a-custom-integration-from-python "
    "to learn how to format your roms directory.",
  )
  args = parser.parse_args()

  retro.data.Integrations.add_custom_path(args.roms_path)
  movie = retro.Movie(args.movie_file)
  movie.step()

  env = retro.make(
    game=movie.get_game(),
    state=None,
    # bk2s can contain any button presses, so allow everything
    use_restricted_actions=retro.Actions.ALL,
    players=movie.players,
    inttype=retro.data.Integrations.ALL,
  )
  env.initial_state = movie.get_state()
  env.reset()

  while movie.step():
    keys = []
    for p in range(movie.players):
      for i in range(env.num_buttons):
        keys.append(movie.get_key(i, p))
    env.step(keys)
